### ISSUE TITLE
backup failed with litespeed

### ISSUE THREAD

**Issue by Polasin** [jelastic-jps/backup-addon#6]
{
    "result": 4109,
    "error": "The operation could not be performed",
    "responses": [{
        "result": 4109,
        "error": "********",
        "errOut": "********",
        "exitStatus": 1,
        "nodeid": xxxxx,
        "out": "Thu Nov 24 10:29:01 +07 2022 env-xxxxxx Creating the manual backup (using the backup addon with commit id xxxxx) on storage node xxxxx \nThu Nov 24 10:29:01 +07 2022 env-xxxx
        Checking the backup repository integrity and consistency before adding the new snapshot\nThu Nov 24 10:29:08 +07 2022 env-xxxxxx  Creating the DB dump\nDB backup process failed.",
        "source": "JEL"
    }],
    "source": "JEL"
}

the error first appear on 22 Nov 2022. I think it might relate to this update https://github.com/jelastic-jps/backup-addon/commit/714f61beaf47165c2b12f86345ca82278c7791bc.

**Comment by DmytroZubelevych** [comment]
Re-checked, not reproduced now
